### ISSUE TITLE
[question] Update form from modal popup

### ISSUE THREAD

**Issue by danielo515** [ermouth/jQuery.my#10]
Hello,

Sorry for not labeling this as question, but I can not add labels.

I am having a very bad experience trying to update a text field from a modal popup. The layout is a bit complex, and I am getting a bit lost tracking how children sees the data object. I'll try to specify the layout:

Form
* Some property
*  Array whit children
 * Single child (columns)
   *  Modal popup

So there are three levels of nested manifest: the main one, the manifest for each column and then another manifest for the modal popup. The modal popup has a button, which bind function perform some stupid calculations, and then stores the result in the data object. The problem is that when the modal closes, the data updated is not reflected on the column (parent). I based the modal in your example of the main website(copy and paste, same _updateMe function), but in it there is no update from any function, just good old object --> fields binding. I don't know if it matters, but I am passing just the whole data object to the modal child manifest.

Also it will be nice if you have time to  explain me how the data object is passed to children. It looks like magic for me when I only have to use "text" (for example) as identifier inside a repeated section, and it is magically bind to the correct item inside the list.

Thank you very much.

**Comment by ermouth** [comment]
1. In cases like this please, provide code as Gist(s) and make it as simple as possible.
2. If your question is not general (and it is not in this case) – write me a letter to ermouth@gmail.com. Since there are some people following this repo, our conversation ping-pong is just flood for them. I see people started to unwatch repo – it‘s not good.

----

In general, modal is a promise. It is:
* resolved when modal closes normally (some control inside triggers event "commit")
* rejected when modal is escaped (closed by `X` button, or `Esc`, or triggering event "cancel" from inside, or you clicked screen dimmer if any).

__Root form does not catch modal close, you must let root know explicitly that it must redraw. It‘s intentional behavior.__ So in your case, when your modal mutates data object of parent form *directly* it can be something like this:

```javascript
$ctrl.modal({
  /*modal params here*/
}).then(function(modalData){
  // Here goes code for normal close
  $ctrl.my().root.my("redraw");
}).fail(function(){
  // Here goes code for escaped close
  $ctrl.my().root.my("redraw");
});
```

If you provided modal with *cloned* data (that is more suitable in most cases), you must apply data, received from the modal, to a caller form – and then redraw entire caller.

> I only have to use "text" (for example) as identifier inside a repeated section, and it is magically bind to the correct item

Did not understand a question. Show the code excerpt, please.
