### ISSUE TITLE
Aria Invalid on input via .my("errors")

### ISSUE THREAD

**Issue by dubrod** [ermouth/jQuery.my#23]
This is more of a suggestion than an issue but i would suggest adding some minor A11Y attributes on the 
`.my("errors")` function.

heres how i did it. 

line 923 - inside `if (r = a.hasClass("my-form-list")` i added the removeAttr here:

```
f.removeClass(y), f.children("input").removeAttr("aria-invalid"),
```

then on line 929 - inside the final `else` i added the attr here:

```
f.addClass(y), u.errors[m] = v;
f.children("input").attr("aria-invalid", "true");
```

of course the user still needs to handle labels properly but im already doing that on my `save` function but this is pretty standard form validation.

Thanks!

**Comment by ermouth** [comment]
Thanks for proposal. Can you please explain what exactly adding aria-related markup gives? 

And seems that you‘re modifying minified js. Why not edit full version?

**Comment by dubrod** [comment]
ARIA elements are essential for accessibility compliant code.
https://www.w3.org/TR/wai-aria/states_and_properties

Very important for forms. 

Just realized the minified thing lol

**Comment by ermouth** [comment]
> Very important for forms.

Well, ARIA codes are just declarations, that are invisible and has no default action for the vast majority of users – so I wouldn‘t say ARIA compliance is important.

However, according to BuiltWith, wai-aria popularity is slowly increasing. Also, surprisingly, adding aria-attributes to DOM elts is enough CPU cheap (it was not so 2 years ago, when I first tested it). 

So I plan to explore how those attrs interfere with rich ui plugins, and, if no conflict discovered, add some aria-related stuff in 1.3.

Thanks for proposal )

**Comment by johs** [comment]
Hi,
a small comment on ARIA: In Norway accessibility to web sites is now mandatory by law. It basically means ARIA is a standard request.
johs

**Comment by dubrod** [comment]
In USA, if your a company that provides a Public Service it is required also. I spend a lot of time now testing and developing for Section 508 and WCAG - https://www.w3.org/WAI/WCAG20/glance/

**Comment by ermouth** [comment]
@dubrod AFAIK in USA the requirement only applies to gov-related structures. And, to say, even root sites of gov agencies mostly do not comply, even health-related (NIH, HRSA, CDC, FDA).

@johs I know that Norway a11y legislation is most stringent in the world. Despite this fact only 4 sites from Alexa top-10 for .no domain have more or less acceptable aria codes inside. 3 has superficial imitation and 3 has no aria at all.

As for Russia, we also have the quite strict law, that obliges to have special versions of gov-related sites for vision-impaired people. As for me, this approach (special websites) is much more reasonable, since we can apply special high-contrast CSS, simplified layout and cursor/action highlighting. This approach seems more helpful for real people with impaired vision, than aria codes, that are both awfully designed and poorly supported by end-user devices.

**Comment by dubrod** [comment]
wrong

**Comment by ermouth** [comment]
Will add some ARIA-related features to 1.3, seems that aria codes produce no conflicts for $.my supported rich ui plugins.

Closing, thanks @dubrod and @johs.
