### ISSUE TITLE
Cannot use Enter in textarea in nested form.

### ISSUE THREAD

**Issue by w1tebear** [ermouth/jQuery.my#34]
I am using jQuery.my to bind to a fairly complex object and really like its functionality. Unfortunately, though, I am having a problem where I am unable to create multi-line input in textareas in nested forms. It works ok in the main form but in my nested, repeated, forms the newlines just get "eaten up" - my cursor goes to the next line then immediately jumps back to the end of the first line. I am hoping that this is something that can be fixed. Thanks!

**Comment by ermouth** [comment]
$.my does not process Enter or other keyboard events in special way, so it seems that reason is outside $.my.

You can easily check it changing `input` to `textarea` in the Page Layout example at jquerymy.com – all works perfect.

So, please, provide more details or a code sample to look into issue more deeply.

**Comment by w1tebear** [comment]
Thank you for your prompt response. This is indeed NOT a problem with $.my but a problem with my own bind function. I apologize for having troubled you.
