### ISSUE TITLE
Recursive rendering models

### ISSUE THREAD

**Issue by antixrist** [ermouth/jQuery.my#8]
Hi!
Tell me, please, how about recursive rendering of forms? For example, resources tree or (theoretically) family tree - where every item has identical properties set in any deep level.
```
{
  fullname: 'Some name',
  age: 25,
  city: 'NY',
  childs: [{ /* array with child objects with identical properties set: 'fullname', 'age', 'city', etc.. */ }]
}
```
Currently, i don't understand how this can be done because every form should have unique id and form controls should bind with properties by unique "id" attribute too. Even if the bind properties by 'class'-selector like:
```
$(".form").my({ui:{
 ".fullname": "fullname",
 ".age": "age"
}}, data);
```
this could lead to conflict with delegated and bubbling events.
Whether there is possibility to recursive handling of this issue?

p.s. sorry for my bad english. I hope you understand me :)

**Comment by ermouth** [comment]
http://cloudwall.me/etc/json-editor.html – its recursive.

It can open self manifest – see left column list. Then you can go to `.$multi` branch and see keys of its `.ui` section members. They look like `.ilist:eq(0)` – that is valid jquery selector.

Please note – this approach implies huge perfomance penalties, this kind of selectors is rather slow, so be cautious. In less general cases `#id` selectors work quite fine since `$obj.find("#id")` finds only first child of `#id`. To find all you must use something like `div#id`.

About bubbling. $.my binds event listeners to controls (not to form) explicitly when starts. It was made to have acceptable perfomance. Since we have to determine what kind of control emitted event – most of them has different internal getters/setters syntax – we better do it once at start, it‘s quiet consuming task.

**Comment by ermouth** [comment]
И да, можно по-русски )
